package rational.enums;

public enum SpecialRuleTypeEnum{
    ALWAYS_STRIKE_FIRST, ALWAYS_STRIKE_LAST, ARMOR_PIERCING, COLD_BLOODED, DEVASTATING_CHARGE, EXTRA_ATTACK, MARTIAL_PROWESS, FEAR, FIGHT_IN_EXTRA_RANKS, FRENZY,
    HEROIC_KILLING_BLOW, HOLD_THE_LINE, IMMUNE_TO_PSYCHOLOGY, IMPACT_HITS, KILLING_BLOW, PREDATORY_FIGHTER, MONSTEROUS_INFANTRY, POISONED_ATTACKS,
    SKIMISHERS, STOMP, THUNDERSTOMP, STRENGTH_IN_NUMBERS, STUBBORN, TERROR, UNBREAKABLE;
}
